
spring.application.name=employ_management

spring.data.mongodb.uri=mongodb+srv://chiragchahar1314_db_user:gMZooBO5Ylh8VfIR@cluster0.icr4xvr.mongodb.net/employeedb?retryWrites=true&w=majority

server.port=8080
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG